# Generated by Django 5.0.2 on 2025-03-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorder',
            name='order',
        ),
        migrations.AddField(
            model_name='courseorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='courseorder',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Credit/Debit Card'), ('UPI', 'UPI Payment'), ('COD', 'Cash on Delivery')], default='CARD', max_length=10),
        ),
        migrations.AddField(
            model_name='courseorder',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
