# Generated by Django 5.0.2 on 2025-03-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_courseorder_order_courseorder_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='video_url',
        ),
        migrations.AddField(
            model_name='content',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
    ]
