# Generated by Django 5.0.2 on 2025-03-09 08:18

from django.db import migrations


def add_sports_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    
    # Create sports categories
    sports_categories = [
        {
            'name': 'Cricket',
            'description': 'Cricket equipment including bats, balls, pads, gloves, and other accessories.'
        },
        {
            'name': 'Baseball',
            'description': 'Baseball equipment including bats, balls, gloves, helmets, and protective gear.'
        },
        {
            'name': 'Football',
            'description': 'Football gear including balls, cleats, shin guards, and jerseys.'
        },
        {
            'name': 'Badminton',
            'description': 'Badminton equipment including rackets, shuttlecocks, nets, and accessories.'
        },
        {
            'name': 'Table Tennis',
            'description': 'Table tennis equipment including paddles, balls, tables, and nets.'
        },
        {
            'name': 'Tennis',
            'description': 'Tennis equipment including rackets, balls, nets, and court accessories.'
        }
    ]
    
    for category_data in sports_categories:
        Category.objects.get_or_create(
            name=category_data['name'],
            defaults={'description': category_data['description']}
        )

def remove_sports_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Category.objects.filter(name__in=[
        'Cricket', 'Baseball', 'Football', 
        'Badminton', 'Table Tennis', 'Tennis'
    ]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RunPython(add_sports_categories, remove_sports_categories),
    ]
